---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todoapp
        image: docker.io/abhinallana/tododjango:v2
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-deployment
spec:
  type: NodePort 
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 8000
      #targetPort: 8000
      nodePort: 31500
