pipeline {
  agent {
      docker {
        image 'python:3.7'
       }
    }
    
  stages {

    stage('CheckOut') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/develop']], extensions: [], userRemoteConfigs: [[credentialsId: 'GithubCreds', url: 'https://github.com/abhinallana/django-todo-devops.git']]])
      }
    }
     
    stage('Build') {
      steps {
        git branch: 'develop', credentialsId: 'GithubCreds', url: 'https://github.com/abhinallana/django-todo-devops.git'
      }
    } 
    stage('Create an Admin') {
      steps {
          sh "pwd"
          } 

    }
    
    stage('Deploy') {
      steps {
         echo 'Check live App on http://127.0.0.1:8000/todos'
         sh 'python manage.py runserver' // http://127.0.0.1:8000/todos to check the running app
      }
    }  
  }
}
